spring.application.name=Cement Inventory App
# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/cement_app
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=8080
